### ISSUE TITLE
1주차 궁금한 점

### ISSUE THREAD

**Issue by ksy90101** [ksy90101/effactive-java-study#2]
아이템 1
> 반환 타입의 하위 타입 객체를 반환할 수 있는 능력이 있다.
- 이거에 대한 좋은 예제가 있을까요?(저희 미션에서!)

아이템 9
>  두 번째 예외가 첫 번째 예외를 완전히 집어삼켜 버린다. 그러면 스택 추적 내역에 첫 번째 예외에 관한 정보는 남지 않게 되어, 실제 시스템에서의 디버깅을 몹시 어렵게 한다.
- 말 자체에 대해 이해가 어렵네요 ㅠㅠ

아이템 16
>  `package-private` 클래스 혹은 private 중첩 클래스라면 데이터 필드를 노출한다 해도 하등의 문제가 없다.
- 그래도 노출하지 않는 게 더 좋지않을까? 왜 문제가 안되는지 잘 모르겠습니다.ㅠㅠ
- 종종 필드를 노출하는 편이 나을때도 있다는데 그 의미를 잘 모르겠습니다 ㅠㅠ

아이템 24
- 중첩클래스를 최대한 피해야 된다고 생각하는데, 다들 생각이 어떠신지!?

**Comment by KS-KIM** [comment]
### 아이템 20
인터페이스를 통한 다중 상속을 하는 경우 복잡한 클래스가 만들어 질 것 같은데, 단일 책임 원칙을 위배하게 되는 것은 아닌가 생각됩니다.

### 아이템 20 ~ 22
언제 인터페이스를 사용하는 것이 좋을까에 대한 논의가 더 필요합니다.

### 아이템 22
A 클래스와 B 클래스의 공통요소를 추출하여 C 추상 클래스를 상속받을 수 있습니다.
공통 요소를 인터페이스로 추출하면 상수를 두는것이 안티 패턴이므로 정적 유틸리티 클래스에 뽑아내야 합니다. 이러한 구조가 괜찮을까요?

### 아이템 23 태그 달린 클래스
체스 보드의 turn을 나타내는 enum타입은 적절하지 않은 것일까? 턴은 보드의 상태를 나타내는 것이고, 도형의 Shape는 형태를 나타내는 것이라 다른 것 같기도 하네요...

**Comment by ksy90101** [comment]
아이템3. 직렬화
아이템3. 리플렉션
아이템7. weak hash map
아이템11. 버킷
